### ISSUE TITLE
Not working on Ubuntu 21.04

### ISSUE THREAD

**Issue by goncalo-oliveira** [carrot69/keep-presence#1]
Hi!

First of all, thank you and great job with this simple and effective tool.

However, since I moved from Ubuntu 20.10 to 21.04, the tool stopped working. I mean, it should be working, according to the logs, as it correctly detects when I'm idle, but the presence action doesn't work. The mouse mode never worked for me in reality, so I used the keyboard mode. But since the update, it doesn't seem to be effective either.

**Comment by YusufMavzer** [comment]
It's because ubuntu 21.04 uses wayland instead of xorg
https://github.com/carrot69/keep-presence/issues/2

**Comment by carrot69** [comment]
I close this issue, we will discuss this problem in #2
