### ISSUE TITLE
Unable to mount tmp folder after reinstalling with snap

### ISSUE THREAD

**Issue by patrickvlt** [carrot69/keep-presence#11]
After removing this package with:

```
sudo snap remove keep-presence
```

And then reinstalling with:

```
sudo snap install keep-presence
```

I constantly get the following error:

```
cannot perform operation: mount --rbind /dev /tmp/snap.rootfs_HdE3tB//dev: No such file or directory
```

I've tried creating the folders in /tmp/ myself, but then when I try to re-launch the application, the path changes in this error and the error will simply reappear.

**Comment by carrot69** [comment]
Do you have the same issue with other snaps?

Can you do:

```snap version```
