### ISSUE TITLE
Package keep-presence for pypi

### ISSUE THREAD

**Issue by nkuttler** [carrot69/keep-presence#12]
It would be cool if this was pip installable, I'd be happy to help with that.

**Comment by carrot69** [comment]
Hi @nkuttler, I like this; I'm gonna take a look at the docs, if I need some help I'm gonna tell you! Thanks!!!

**Comment by carrot69** [comment]
@nkuttler just added this, check if it's working correctly for you, as it's my first time with pypi:

 https://github.com/carrot69/keep-presence/tree/master#install-from-pypi

**Comment by nkuttler** [comment]
Works fine, thanks!
