### ISSUE TITLE
package available for arch linux

### ISSUE THREAD

**Issue by ftschindler** [carrot69/keep-presence#14]
Just a note: I created a package for archlinux: https://aur.archlinux.org/packages/keep-presence

Feel free to ping me if you think anything should be changed there (and to close this issue after reading).

**Comment by SwapnilSoni1999** [comment]
Its not working with plasma cant see mouse moving

**Comment by ftschindler** [comment]
> Its not working with plasma cant see mouse moving

If it's an issue with packaging, please report this in the AUR. If it's an issue with the software, I suggest to open up a new issue for this, as this is really just a public note to @carrot69 to inform about the presence of the packaging...

**Comment by carrot69** [comment]
> Just a note: I created a package for archlinux: https://aur.archlinux.org/packages/keep-presence
> 
> Feel free to ping me if you think anything should be changed there (and to close this issue after reading).

Looks perfect to me, thanks ;D
