### ISSUE TITLE
Please consider adding keep-presence to the PYPI registry

### ISSUE THREAD

**Issue by yurivict** [carrot69/keep-presence#16]
Users should be able to install ```keep-presence``` using pip.

**Comment by carrot69** [comment]
Yes, we keep this in mind; we are working on it, but it will take some time.

I'm going to close this, since there's another issue open with this.

https://github.com/carrot69/keep-presence/issues/12

**Comment by carrot69** [comment]
https://github.com/carrot69/keep-presence/tree/master#install-from-pypi

**Comment by carrot69** [comment]
@yurivict https://github.com/carrot69/keep-presence/tree/master#install-from-pypi

tell me if it's working fine for you; thanks! ;)
