### ISSUE TITLE
Daemon mode

### ISSUE THREAD

**Issue by cjohnston1158** [carrot69/keep-presence#7]
It would be nice to have a daemon mode.

**Comment by carrot69** [comment]
To run it as a daemon, you can just: 

```
keep-presence -c -s2 -p10 > /dev/null &
```

Do you see any advantage to have that option? 
What would that be?

**Comment by carrot69** [comment]
To run it as a daemon, you can just: 

```
nohup keep-presence -c -s2 -p10 &> /dev/null &
```

Knowing that, do you see any advantage if we add the run-as-daemon option? 
What would that be?

**Comment by cjohnston1158** [comment]
Other than cleaner/easier, no, not really.

**Comment by carrot69** [comment]
@cjohnston1158 this will need some changes on the code... I want to do a refactor of the code, maybe I can add this feature then; I'll think about this, thanks!
